---
- name: open nxserver ports for all in ufw
  ufw:
    rule: allow
    port: "{{ item |string }}"
    # allow both tcp (main) and udp (multimedia)
    #proto: tcp
  no_log: "{{ hide_secrets |bool }}"
  loop: "{{ lin_nxserver_ports }}"
  # workaround for ufw failures on xenial on github runners
  register: ufw_result
  until: ufw_result is successful
  when: lin_firewall == 'ufw'

- name: open nxserver ports for internal/external hosts in ferm
  ferm_port:
    port: "{{ lin_nxserver_ports }}"
    domain: "{{ lin_nxserver_direct |bool |ternary('external','internal') }}"
    exclusive: true
    comment: nxserver
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: block/unblock nxserver ports from external hosts in ferm
  ferm_port:
    port: "{{ lin_nxserver_ports }}"
    domain: blocked
    state: "{{ lin_nxserver_direct |bool |ternary('absent','present') }}"
    exclusive: false
    comment: nxserver
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
...
